services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    networks:
      - webui-net
    ports:
      - "8080:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      MCP_ENABLE: "true"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: pi
      POSTGRES_PASSWORD: raspberry
      POSTGRES_DB: mydb
    volumes:
      - my-postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - webui-net

  postgres-mcp:
    build: ./mcpo
    container_name: postgres-mcp
    restart: always
    environment:
      DATABASE_URI: "postgresql://pi:raspberry@postgres:5432/mydb"
    networks:
      - webui-net
    ports:
      - "8001:8000"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - webui-net
    command: tunnel run --token ${CLOUDFLARE_TOKEN}

volumes:
  open-webui:
    external: true
  my-postgres-data:
    external: true

networks:
  webui-net:
    name: webui-net
    driver: bridge
